services:
  blogsite:
    image: badgers-hugo-template
    container_name: blogsite
    env_file:
      - .env
    build:
      context: .
    volumes:
      - "./website:/blogsite/"
    ports:
      - "1313:1313"
      - "8080:80"
      - "35729:35729"